---
proxy-providers:
  GLOBALSSH:
    type: file
    path: "./proxy_provider/akrab.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: GLOBALSSH
  type: url-test
  strategy: consistent-hashing
  disable-udp: false
  use:
  - GLOBALSSH
  url: http://www.gstatic.com/generate_204
  interval: '300'
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "+.*"
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 192.168.8.1
  - 10.0.124.193
  - 192.168.9.1
  - 114.114.114.114
  - 119.29.29.29
  nameserver:
  - dhcp://"eth1"
  - 192.168.8.1
  - 8.8.4.4
  - 8.8.8.8
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: putra
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: false
auto-route: true
profile:
  store-selected: true
  store-fake-ip: true
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- DST-PORT,9993,GLOBAL
- SRC-IP-CIDR,192.168.1.1/32,DIRECT
- SRC-IP-CIDR,198.18.0.1/32,DIRECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,Direct,DIRECT
- RULE-SET,Reject,REJECT
- MATCH,GLOBAL
rule-providers:
  Direct:
    type: file
    behavior: classical
    path: "./rule_provider/direct.yaml"
  Reject:
    type: file
    behavior: classical
    path: "./rule_provider/reject.yaml"
unified-delay: true
geodata-mode: false
geodata-loader: standard
tcp-concurrent: true
tun:
  enable: true
  stack: gvisor
  device: utun
  mtu: 65535
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
